### ISSUE TITLE
How do I edit the Service Manager environments connection parameters?

### ISSUE THREAD

**Issue by neotherack** [noxify/servicemanager-vscode-extension#2]
I just created the restful webservice and installed the SM VSCode extension.
I'm now stuck on the sm9 environment settings configuration, it's pointed to localhost but that doesn't match my current situation.

Could you help me on how to edit these extension settings?

**Comment by Praphull1** [comment]
Hello Neotherack,

You can goto the settings option into the vscode by pressing the CTRL+; keys. Then click on the {} option from top right corner and add the below lines to it and save.

{
    "servicemanager" : {
        "environments" : {
            "env1": {
                "name": "Desktop-Prafull",
                "url": "http://localhost:13080/SM/9/rest/",
                "resourceCollection": "ScriptLibrary",
                "resourceName": "ScriptLibrary",
                "username": "intAdmin",
                "password": "intAdmin",
                "path": "/Users/Prafull/OneDrive - Serviceberry Technologies Pvt. Ltd/Documents/desktop-prafull/",
                "defaultPackage" : "User",
                "fields" : {
                    "name" : "Name",
                    "package" : "Package",
                    "script" : "Script"
                }
            },
            "env2": {
                "name": "HMC-Dev",
                "url": "http://172.24.2.57:13080/SM/9/rest/",
                "resourceCollection": "ScriptLibrary",
                "resourceName": "ScriptLibrary",
                "username": "falcon",
                "password": "P@ssw0rd1234",
                "path": "/Users/Prafull/OneDrive - Serviceberry Technologies Pvt. Ltd/Documents/HMC-Dev/",
                "defaultPackage": "User",
                "fields": {
                    "name": "Name",
                    "package": "Package",
                    "script": "Script"
                }
            },
            "env3": {
                "name": "HMC-Test",
                "url": "http://172.24.4.110:13080/SM/9/rest/",
                "resourceCollection": "ScriptLibrary",
                "resourceName": "ScriptLibrary",
                "username": "falcon",
                "password": "P@ssw0rd12345",
                "path": "/Users/Prafull/OneDrive - Serviceberry Technologies Pvt. Ltd/Documents/HMC-Test/",
                "defaultPackage": "User",
                "fields": {
                    "name": "Name",
                    "package": "Package",
                    "script": "Script"
                }
            }
        }
    }

**Comment by neotherack** [comment]
Nice! it's now working.

Thanks a lot!
