### ISSUE TITLE
Need one more option for Execution

### ISSUE THREAD

**Issue by Praphull1** [noxify/servicemanager-vscode-extension#3]
Dear,

I have configured the new process and state in Service Manager for the execution of Script Library, and assigned it to the Compile option in web service configuration page, as currently i am not sure how to add new option in vscode service manager extension.

Request you to add new option in vscode Service Manager Extension as execute for the executing the script.

Thanks,
Prafull Patil

**Comment by neotherack** [comment]
+1

**Comment by noxify** [comment]
Hi,

Sorry for the delay. I will check it in the next days.

**Comment by noxify** [comment]
Hi @Praphull1 and @neotherack,

I'm sorry for the delay. 

With the latest version (2.0.1) you can execute the script directly from your vsc.
Please check the README for detailed instructions.

Thanks!
